export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE"
export const SET_ITEMS_CARD = "SET_ITEMS_CARD"
export const SET_ITEMS_FAVORITES = "SET_ITEMS_FAVORITES"

