export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE"
export const SET_ITEMS_CART = "SET_ITEMS_CART"
export const CLEAR_ITEMS_CART = "CLEAR_ITEMS_CART"
export const SET_ITEMS_FAVORITES = "SET_ITEMS_FAVORITES"
export const SPINNER_ON = "SPINNER_ON"
export const SPINNER_OFF = "SPINNER_OFF"

